service: metadata-scraper

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 25

functions:
  scraper:
    handler: api/url-scraper.scraper
    events:
      - httpApi:
          path: /url-metadata-scraper
          method: post 
